load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "sham_tests",
    size = "small",
    srcs = [
        "queue_mpmc_test.cpp",
        "queue_spsc_test.cpp",
        "shared_memory_buffer_test.cpp",
        "shared_memory_test.cpp",
        "test_helpers.h",
    ],
    deps = [
        "//src/adapters:adapters",
        "//src/sham:sham",
        "@googletest//:gtest_main",
    ],
)
